### ISSUE TITLE
Example of LSODA

### ISSUE THREAD

**Issue by luzechao** [lh3/misc#1]
Hi, I wonder if you can provide an example using your simplified interface of the LSODA solver. Could you also explain what each input variable means? Thank you so much.

**Comment by lh3** [comment]
Here is some simple explanation. I will try to find an example later (I am heading to a meeting).

``` c
/**
 * Solve ODE \vec{y}'=\vec{f}(x,\vec{y})
 *
 * @param y      \vec{y} at x0
 * @param n      dimension of \vec{y}
 * @param x      x0; on return, x is set to x+step
 * @param xout   xout-(*x) is the max step
 * @param eps    precision
 * @param yscal  scaling vector; set to [1,1,1,...] if unsure.
 * @param devis  function \vec{f}(x,\vec{y})
 * @param data   local data needed for $devis.
 *
 * @note C function devis(x,\vec{y},\vec{y}',data) computes \vec{y}'=\vec{f}(x,\vec{y}).
 */
int n_lsoda(double y[], int n, double *x, double xout, double eps, const double yscal[], _lsoda_f devis, void *data);
```

**Comment by luzechao** [comment]
Thank you so much. My problem has already been solved. I actually wrote a c++ wrapper to that LSODA solver. For the C function devis(x,\vec{y},\vec{y}',data), I pass the whole system class to the void pointer data, it works well after all. Thank you so much for sharing the useful snippet. Your blog is also very helpful.
